### ISSUE TITLE
cron jobs on tethys servers

### ISSUE THREAD

**Issue by rileyhales** [BYU-Hydroinformatics/ServerIssueTracker#11]
I need to set a cron job to run every day around midnight utah time. i know what it needs to do but i've never made one of these before so i'm not sure how. Wade's cron job issue earlier had some comments about maybe having jameson manage these. could we make that happen? Who should i ask to get a tutorial in setting one of these up?

The cron job will run a python workflow thats currently run manually from within an app which will download and process a bunch of data that the app uses.

**Comment by danames** [comment]
This would definitely be a good think for Jameson to learn how to do and
manage - also so he can train his replacement to do it in the future. I
know Rohit has skills in this area, so maybe he can help too. - Dan
**********************************************************************
Daniel P. Ames, Ph.D., P.E.
Professor, Civil & Environmental Engineering,Brigham Young University,
Provo, Utah, USA
President, International Environmental Modelling & Software Society
Editor-in-Chief, Environmental Modelling & Software
http://ceen.et.byu.edu/faculty/person/Daniel-P.-Ames
<http://ceen.et.byu.edu/content/dan-ames>
http://www.researchgate.net/profile/Daniel_Ames
http://scholar.google.com/citations?user=S0GUCeUAAAAJ

**********************************************************************
