### ISSUE TITLE
THREDD Contour Lines Not Rendering in Groundwater Apps on Tethys-Staging Server

### ISSUE THREAD

**Issue by swainn** [BYU-Hydroinformatics/ServerIssueTracker#12]
A few weeks ago @njones61 sent me the following description of an issue with the groundwater apps on Tethys Staging. I'm posting it as an issue here so we can coordinate on it better.

We are having some issues with our Groundwater Apps. We have a portal here:

http://tethyswa.servirglobal.net/apps/

Notice that when we render the image we get contour lines:

![image](https://user-images.githubusercontent.com/5123221/111487726-37bed300-86fe-11eb-8667-a6e4b5918a0b.png)

We also have the apps on Tethys-staging. This is the GRACE app:

![image](https://user-images.githubusercontent.com/5123221/111487903-5cb34600-86fe-11eb-9005-cd65bbb92eda.png)

Note that there are no contours. @SarvaPulla said that this is an issue with server settings for either GeoServer or THREDDS (can’t remember which). Do you know what we need to do to fix this?

**Comment by swainn** [comment]
Here's what @SarvaPulla and I discovered during our initial investigation:

We looked at the configuration of the Tethys Staging THREDDS server and there don't appear to be any major differences or obvious red flags in how it is configured. I also looked at the failing WMS GetMap requests and discovered they are returning long nasty Java errors. 

The THREDDS server is currently on version 4.6.14. There are two newer versions that I'd like to try installing to see if perhaps this is a bug that is addressed in later versions.

Here are a few more observations gleaned from that investigation:

- GetMap request with style "contour" raises error:
    - https://tethys-staging.byu.edu/thredds/wms/data/grace/grace/utah/utah_csr_tot.nc?service=WMS&request=GetMap&layers=lwe_thickness&styles=contour%2Fgrace&format=image%2Fpng&transparent=true&version=1.1.1&numcontours=20&colorscalerange=-25%2C25&time=2002-05-10T00%3A00%3A00.000Z&width=256&height=256&srs=EPSG%3A4326&bbox=-113.90625,37.71859032558816,-112.50000000000001,38.82259097617713
- Change "contour" to "boxfill" in same failing GetMap request and it "works":
    - https://tethys-staging.byu.edu/thredds/wms/data/grace/grace/utah/utah_csr_tot.nc?service=WMS&request=GetMap&layers=lwe_thickness&styles=boxfill%2Fgrace&format=image%2Fpng&transparent=true&version=1.1.1&numcontours=20&colorscalerange=-25%2C25&time=2002-05-10T00%3A00%3A00.000Z&width=256&height=256&srs=EPSG%3A4326&bbox=-113.90625,37.71859032558816,-112.50000000000001,38.82259097617713
- Not all "contour" GetMap requests fail. If there are no contours, then a blank image is returned. This suggests the error has something to do with generating the contours or perhaps styling them.
    - https://tethys-staging.byu.edu/thredds/wms/data/grace/grace/utah/utah_csr_tot.nc?service=WMS&request=GetMap&layers=lwe_thickness&styles=contour%2Fgrace&format=image%2Fpng&transparent=true&version=1.1.1&colorscalerange=-25%2C25&time=2002-04-16T00%3A00%3A00.000Z&width=256&height=256&srs=EPSG%3A3857&bbox=-12523442.714243278,4696291.017841231,-12210356.646387197,5009377.085697314
- GetLegendGraphic request is also failing with an error:
    - https://tethys-staging.byu.edu/thredds/wms/data/grace/grace/utah/utah_csr_tot.nc?REQUEST=GetLegendGraphic&LAYER=lwe_thickness&PALETTE=grace&COLORSCALERANGE=-25,25

**Comment by swainn** [comment]
I posted an issue on the THREDDS GitHub repository and got quite a bit of helpful feedback: https://github.com/Unidata/thredds/issues/1353

**Comment by swainn** [comment]
Here's another update on my efforts with this issue:

1. I manually backed up the thredds_data directory (see /home/civil/thredds_data-bak.tar.gz)
2. I updated the THREDDS docker image to newer versions: first to 4.6.15, then to 4.6.16.1. Upgrading was the suggestion I received from the issue I posted (see: https://github.com/Unidata/thredds/issues/1353#issuecomment-786327494).
3. The legend image started working after updating, but the contours are still not rendering in the app. Using the Network tab in the debugger shows that the GetMap requests with style=contour are still failing with a 403 status code.

![image](https://user-images.githubusercontent.com/5123221/111488786-2de99f80-86ff-11eb-85b5-81a29aecb00d.png)

4. However, manually running any of the failing contour requests in a new tab works fine. (e.g.: https://tethys-staging.byu.edu/thredds/wms/data/grace/grace/kenya/kenya_csr_tot.nc?service=WMS&request=GetMap&layers=lwe_thickness&styles=contour%2Fgrace&format=image%2Fpng&transparent=true&version=1.1.1&numcontours=20&colorscalerange=-25%2C25&time=2002-04-16T00%3A00%3A00.000Z&width=256&height=256&srs=EPSG%3A4326&bbox=22.5,0,45,21.94304553343818)

5. It seems we have resolved the issue with TDS rendering the contour tiles by upgrading it, but there is some issue with the communication between the app and the THREDDS server. This is the latest suggestion on the issue: https://github.com/Unidata/thredds/issues/1353#issuecomment-786726199. I plan to investigate that next.

**Comment by swainn** [comment]
@rfun and @rileyhales I haven't done anything on this issue for a few weeks after the issues we had with the THREDDS server. I'd like to resume looking into this which may require fiddling with the THREDDS server. I can do this after hours and on the weekends. Are there any times/days coming up I should avoid? Big presentations or times when Tethys Staging will be needed?

**Comment by rileyhales** [comment]
We're passed thesis defenses and all the trainings i'm aware so i don't think there are any particularly important times to be aware of.

In the long term, If you have a rough idea of when you'll be working on server things you could post to the lab's slack about it. I was thinking perhaps we can consolidate the many slack channels we've made for tech issues. We can rename the one we've been using so far to "technology-managers" or something like that which we use for discussions and making plans and stuff. Then perhaps another called like "technology-announcements" used strictly for giving alerts when someone is about to intentionally take things offline or be working on computers in the lab or something. We can reserve reporting issues for github. Giving some amount of forewarning on slack might alleviate confusion and give people a chance to make alternate plans and chat if the server work will cause issues for someone. It would only work if we each commit to giving warning through that channel. Whether its on slack or otherwise, some kind of announcement mechanism would be useful.

**Comment by swainn** [comment]
@rileyhales

**Comment by swainn** [comment]
Updating the THREDDS server on tethys-staging to version 4.6.16.1 seems to have resolved the contour generating error that we were seeing before. However, there seems to be a CORS issue when accessing via Chrome. However, I have noticed that the contours render when accessing via Firefox. For example try viewing this page in Chrome vs. Firefox: https://tethys-staging.byu.edu/apps/newgrace/region/?region-select=24

The difference between Chrome and Firefox is that Chrome has recently implemented more stringent default Referrer-Policy for secure sites: https://developers.google.com/web/updates/2020/07/referrer-policy-new-chrome-default. I'm guessing this is not an issue on the SERVIR portal b/c their portal is not secure (https).

The NGINX configuration for tethys-staging likely needs to be tweaked to handle this properly. See: https://github.com/Unidata/thredds/issues/1353#issuecomment-792902182

Next steps are for me to review the NGINX configuration.

**Comment by swainn** [comment]
The problem seemed to be caused by Chrome setting the Origin header and the THREDDS server choking on it since it was proxied. I was able to resolve this by removing the `Origin` header from the nginx configuration section in `tethys_nginx.conf`:

```
    # THREDDS DATA SERVER
    location /thredds {
        proxy_set_header X-Real-IP  $remote_addr;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header Origin "";
        proxy_pass http://127.0.0.1:7000/thredds;
    }
```
