### ISSUE TITLE
statistics_calculator app on Tethys-Staging, need pull

### ISSUE THREAD

**Issue by pythonweb2** [BYU-Hydroinformatics/ServerIssueTracker#2]
I would like to test changes on my app, so could the new changes be pulled into tethys-staging?

**Comment by rfun** [comment]
Hey, is your app python 3 compatible? Tethys staging is currently down since I was moving it over to the latest tethys. I am probably going to do a clean install on it. So if your app is python 3 compatible, i will install python3 env, else i will do python 2

**Comment by pythonweb2** [comment]
My app is python 3 compatible.

**Comment by rfun** [comment]
Sorry this took so long but the application is installed on http://tethys-staging.byu.edu/apps/statistics-calc

**Comment by rfun** [comment]
It should also work on the https link
https://tethys-staging.byu.edu/apps/statistics-calc/
