### ISSUE TITLE
Need to learn how to install an app on a server and modify Thredds

### ISSUE THREAD

**Issue by rileyhales** [BYU-Hydroinformatics/ServerIssueTracker#4]
I have an app ready to be installed on the server but i'm going to need someone that knows how to install on the server show me how. This app will also require showing netcdf files that i can copy to the server but need to be shown where the catalog.xml file for thredds is so that i can include the right file extensions/dataset scan locations.

app is at
https://github.com/rileyhales/malariapredictor

**Comment by rfun** [comment]
I have sent you instructions for install and thredds. Please reopen the issue if we still need to work on something. Also I will be in on Monday so we can tackle it then
