### ISSUE TITLE
tethys-staging acces.

### ISSUE THREAD

**Issue by jorgessanchez7** [BYU-Hydroinformatics/ServerIssueTracker#6]
I would like to have access to tethys-staging to prove apps before installing them on tethys. I am also a little bit worried about the tethys-staging geoserver, it has been out for a while.

**Comment by rfun** [comment]
Sent user account..Checking geoserver

**Comment by rfun** [comment]
Geo server is also up now. http://tethys-staging.byu.edu/geoserver

Admin/password : admin/geoserver

Please feel free to change it as you deem necessary

**Comment by jorgessanchez7** [comment]
Good.
