### ISSUE TITLE
Need chron job on Tethys server

### ISSUE THREAD

**Issue by pythonweb2** [BYU-Hydroinformatics/ServerIssueTracker#7]
We need a chron task to be placed on the Tethys server for our capstone project. Jared Lillywhite has sent you a zipped file with the necessary files to run the task. You will need to change the path to output the files in the thredds server so that we can access them in our app. You may want to create a new environment (python 2.7) with the requirements that we have listed in the requirements.txt file, just to make sure that we can be sure that we don't run into issues with versions. 

Whichever environment you use to run the code, you will need to change the path to that environment at the top of the code.

**Comment by pythonweb2** [comment]
In progress, @rfun I think I can take care of this one, and we need it asap.

**Comment by pythonweb2** [comment]
@rfun task was placed in root chrontab, daily frequency at 14:03. See /var/log/syslog for logs of the chrontasks. Also, I created a new environment named `Yaque_Del_Norte_Viewer_Cron` with the same miniconda interpreter that was used to create the tethys environment.

**Comment by rfun** [comment]
Sounds good :) We should probably have some documentation somewhere about the cron jobs installed in this server. this is a good place to take help from Jameson, or is he working on something else?
